hibernate:
  connection:
    autocommit: true

spring:
  datasource:
    driverName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/airport
    login: postgres
    password: good
    initialSize: 10
    maxActive: 7
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true





