spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airport?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    login: postgres
    password: good
    initialSize: 10
    maxActive: 7
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

---
logging:
  level:
    ROOT: info
    org.springframework: info
    org.hibernate: info
