spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airport?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    login: postgres
    password: good
    initialSize: 10
    maxActive: 7

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    locations: common.src.main.resources.db.migration
    check-location: true

---
logging:
  level:
    ROOT: debug
    org.springframework: info
    org.hibernate: info

---
jwt-token:
  secret: secret
  expire: 63000000