spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airport?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    login: postgres
    password: good
    initialSize: 10
    maxActive: 7
  jpa:
    hibernate:
      ddl-auto: validate
      use_second_level_cache: false
      region_factory_class: net.sf.ehcache.hibernate.EhCacheRegionFactory
      provider: org.ehcache.jsr107.EhcacheCachingProvider
    show-sql: true
  mail:
    host: smtp.yandex.ru
    username: oglorn@yandex.ru
    password: 1234Qwer
    port: 465
    protocol: smtps
    debug: true



---
logging:
  level:
    ROOT: info
    org.springframework: info
    org.hibernate: info

---
jwt-token:
  secret: SecretKey
  expire: 2000000000
  prefix: "Bearer "
  header: Authorization

---
character_of_place: ABCDEFGHIJKL